- components/Board/Board.jsx
- components/Board/board.js
- components/Board/selectSquare.js
- components/BoardSquare/BoardSquare.jsx
- package-lock.json
- pieces/Bishop.js
- pieces/King.js
- pieces/Knight.js
- pieces/Pawn.js
- pieces/Piece.js
- pieces/Queen.js
- pieces/Rook.js
> 12 display all valid moves for the piece that is selected

- components/Board/Board.jsx
- components/Board/handleCheckmate.js
- components/Board/selectSquare.js
- pieces/Bishop.js
- pieces/King.js
- pieces/Knight.js
- pieces/Pawn.js
- pieces/Queen.js
- pieces/Rook.js
implements isCheck function in king class
king is not allowed to move into check
> 14 check for valid move is in check is it checkmate

- components/Board/selectSquare.js
- pieces/King.js
- pieces/Rook.js
This PR allows the king to castle queenside or kingside
- creates canCastleKingside and canCastleQueenside in King class
- invokes this function in king.getValidMoves and if true, adds the square that the king would land on if castling to the list of validMoves.
Adds logic to selectSquare that checks if the move played is a castling move and if it is, selectSquare updates the rook and king 
positions on the board
> 15 implement castling

- components/Board/Board.jsx
- components/Board/selectSquare.js
- components/Logger/Logger.jsx
- components/Logger/Move.jsx
- components/Logger/toChessNotation.js
- log player moves using chess notation
- user can click a move and see the board state right after that move was committed
- user cannot make a move in a detached head state
- creates Logger and Move components 
- Modifies selectSquare function and adds stateful vars to Board component
- Styles Logger and Move components
image of board with logger
image of what happens if user tries to make move in detached head state
> 23 time travel

- components/Board/Board.jsx
- components/BoardSquare/BoardSquare.jsx
- package-lock.json
- package.json
> 21 board orientation for black

- .gitignore
- App.js
- babel.config.js
- components/Chat/Chat.jsx
- components/Login/Login.jsx
- components/Main/Main.jsx
- components/Main/MainHeader.jsx
- components/Main/PlayGameOptions.jsx
- components/Profile/GameStat.jsx
- components/Profile/Stats.jsx
- components/Profile/StatsCard.jsx
- components/Register/Register.jsx
- components/websocket.js
- package-lock.json
- package.json
> 31 prove that we can respond to emitted messages from the backend

- components/Board/Board.jsx
- components/Board/PlayerCard.jsx
- components/Board/fenToJSON.js
- components/Board/selectSquare.js
- components/Board/socketHandler.js
- components/Main/Main.jsx
- components/Main/MainHeader.jsx
- components/Register/Register.jsx
- types/Actions.js
> 40 selectsquare emits and implement sockethandler

- components/Board/Board.jsx
- components/Board/BoardStyles.js
- components/Board/ChatContainer.jsx
- components/Board/ChatMessage.jsx
- components/Board/handleSendChat.js
- components/Board/socketHandler.js
- types/Actions.js
> 44 chat component

- components/Board/Board.jsx
- components/Board/ChatContainer.jsx
- components/Board/board.js
- components/Board/fenToJSON.js
- components/Board/selectSquare.js
- components/Board/socketHandler.js
- pieces/Bishop.js
- pieces/King.js
- pieces/Knight.js
- pieces/Pawn.js
- pieces/Piece.js
- pieces/Queen.js
- pieces/Rook.js
Implements En-Passant (wip)
Fixes chatContainer component
> 34 en passant

- components/Board/Board.jsx
- components/Board/localSelectSquare.js
- components/Board/selectSquare.js
- components/Board/selectSquareAlgs.js
- components/Board/socketHandler.js
refactors the selectSquare function by creating helper functions in another file.
Board component's state is correctly set for a player retuning to a game they disconnected from
> 46 refactor the selectsquare function

- components/Board/Board.jsx
- components/Board/BoardStyles.js
- components/Board/fenToJSON.js
- components/Board/socketHandler.js
- components/Login/Login.jsx
- components/Main/MainHeader.jsx
- components/Profile/GameStat.jsx
- components/Profile/Stats.jsx
- components/Register/Register.jsx
- components/RightSideBar/GameControls.jsx
- components/RightSideBar/MoveLog.jsx
- components/Timer.jsx
- components/axiosInstance.js
- components/websocket.js
- types/Actions.js
Adds timers to the board component
> 16 timers on game page

- components/Board/Board.jsx
- components/Board/fenToJSON.js
- components/Board/socketHandler.js
- components/Profile/ArchivedGamesContainer.jsx
- components/Profile/GameStat.jsx
- components/Profile/Stats.jsx
- components/axiosInstance.js
- components/websocket.js
- types/TimeControls.js
> feat: update time and refactor archivedgames container (#54)

- App.js
- components/Board/Board.jsx
- components/Main/MainHeader.jsx
- components/Profile/ArchivedGamesContainer.jsx
- components/Profile/GameStat.jsx
- components/Profile/Stats.jsx
- components/axiosInstance.js
> chore: update axios instance (#56)

- components/Board/Board.jsx
- components/Board/selectSquare.js
- components/Board/selectSquareAlgs.js
- components/PromptModal/PromptModal.jsx
- components/PromptModal/handlers.js
- pieces/Pawn.js
- socket/socketFunctions.js
- socket/socketHandler.js
- socket/websocket.js
- views/gameView/onlineGameView/OnlineGameView.jsx
- Implements promotion feature allowing player to select between a knight and queen upon promotion from a prompt modal
- alters the PromptModal component to support promotion as a prompt type
- extracts the handlers from the PromptModal.jsx into a sister file called "handlers.js" 
- passes prompt setters down as props from OnlineGameView -> Board -> selectSquare -> PromptModal  
NEED TO MAKE CHANGE ON BACKEND: 
```java
private boolean isMoveLegal(String move) {
if (move.length() < 4) return false;
if (move.length() == 5 || move.length() == 6) { // promotion
move = move.substring(0, 4);
}
return board.validMoves().stream().map(Board.Move::uci).toList().contains(move);
}
```
> 70 promotion

- components/Board/Board.jsx
- components/Board/selectSquare.js
- components/Board/selectSquareAlgs.js
- components/Main/PlayGameOptions.jsx
- components/Profile/ArchivedGameCard.jsx
- components/Profile/ArchivedGamesContainer.jsx
- components/Profile/GameStat.jsx
- components/Profile/GameStatStyles.js
- components/PromptModal/PromptModal.jsx
- components/gameOverModal/GameOverModal.jsx
- views/gameView/onlineGameView/OnlineGameView.jsx
- style the GameStat component kind of
- fix ArchivedGamesContainer's fetch request
- implement "new game" button on GameOverModal
- properly display draws on archived game cards 
Still need to implement "rematch" button on GameOverModal
> 68 rematch and new game

- components/Board/Board.jsx
- components/Board/selectSquare.js
- components/Timer/Timer.jsx
- socket/socketFunctions.js
- views/gameView/onlineGameView/OnlineGameView.jsx
- Adds isGameOver state to OnlineGameView
- passes this state to timers and to selectSquare function to freeze the timers and prevent users from being able to make moves
if isGameOver is true
> 69 gracefully handle game ending

- components/Board/PlayerCard.jsx
- components/RightSideBar/MoveLog.jsx
- components/RightSideBar/MoveLogItem.jsx
- views/gameView/gameReview/ReviewGameStyles.js
- views/gameView/gameReview/ReviewGameView.jsx
- views/gameView/onlineGameView/OnlineGameView.jsx
This pr cleans up the review game page
> feat: update review game css (#79)

- App.js
- components/Main/MainHeader.jsx
- components/Profile/ArchivedGameCard.jsx
- components/Profile/ArchivedGamesContainer.jsx
- components/Profile/Profile.jsx
- components/Profile/Stats.jsx
- package-lock.json
- package.json
> fix: clean up stats page (#91)

- components/Header/Header.jsx
- package-lock.json
- package.json
- services/pieces/Rook.js
> fix: small fixes (#95)

- components/Board/Board.jsx
- components/Board/board.js
- components/BoardSquare/BoardSquare.jsx
- screens/GameReviewScreen/ReviewGameScreen.jsx
- screens/OnlineGameScreen/OnlineGameScreen.jsx
> fix: fix stuff (#97)
